const popupTypes = {
  GENERAL_MESSAGE: 'GENERAL_MESSAGE',
  API_ERROR: 'API_ERROR',
  API_MESSAGE: 'API_MESSAGE',
  TWO_ACTION: 'TWO_ACTION',
  NEW_USER: 'NEW_USER',
  NEW_FIELD: 'NEW_FIELD',
  NEW_BID: 'NEW_BID',
  NEW_DISTRIBUTOR: 'NEW_DISTRIBUTOR',
  NEW_BLOCKED: 'NEW_BLOCKED',
  APPROVE_CONDITIONS: 'APPROVE_CONDITIONS',
  CONFIRM_ACTION: 'CONFIRM_ACTION',
  MANAGE_NAMESPACES: 'MANAGE_NAMESPACES',
  DUPLICATE_NAMESPACE: 'DUPLICATE_NAMESPACE',
};

export default popupTypes;
